package:
  name: talosctl
  version: "1.10.7"
  epoch: 0
  copyright:
    - license: MPL-2.0
environment:
  environment:
    CGO_ENABLED: "0"
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/siderolabs/talos
      tag: v${{package.version}}
      expected-commit: 71de2e23bab510d850ab7d96c33f33f9601e2dc0
  - uses: go/build
    with:
      packages: cmd/talosctl/main.go
      output: talosctl
      tags: grpcnotrace
  - uses: strip
update:
  enabled: true
  github:
    identifier: siderolabs/talos
    strip-prefix: v
